1. Create a 4X2 integer array and Prints its attributes
Note: The element must be a type of unsigned int16. And print the
following Attributes. 
The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.


In [1]:
import numpy as np
arr = np.array([[1,2],[2,3],[3,4],[4,5]])
arr

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [2]:
np.shape(arr)

(4, 2)

2. Note: The element must be a type of unsigned int16. And print the
following Attributes. The shape of an array.

In [6]:
np.ndim(arr)

2

In [10]:
np.size(arr)

8

In [11]:
arr.itemsize

4

2. Create a 5X2 integer array from a range between 100 to 200 such that the
difference between each element is 10.


In [12]:
arr_2 = np.arange(100,200,10)
arr_2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [13]:
arr1= arr_2.reshape(5,2)
arr1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

3. Following is the provided numPy array. Return array of items by taking the
third column from all rows
* sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])


In [15]:
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [16]:
arr = arr.flatten()
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

4. Extract all odd numbers from arr
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    
    

In [26]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
for i in arr:
   
    if i%2!=0:
        
        print(i)

1
3
5
7
9


5. Create a null vector of size 10


In [29]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

5. Create a null vector of size 10 but the fifth value which is 1

In [55]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1

In [56]:
null_vector1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49


In [32]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Create a 3x3 identity matrix

In [33]:
m = np.eye(3,3)

In [34]:
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values

In [40]:
a = np.random.random((3,3,3))

In [41]:
a

array([[[0.63928264, 0.60731186, 0.25952077],
        [0.32696836, 0.04189999, 0.53968386],
        [0.3090973 , 0.27174355, 0.93215781]],

       [[0.44432376, 0.23791921, 0.01672282],
        [0.47032231, 0.10042588, 0.94293996],
        [0.66928431, 0.8583327 , 0.42172125]],

       [[0.52631337, 0.63759978, 0.54651942],
        [0.38532488, 0.9469443 , 0.44330142],
        [0.00857222, 0.83077895, 0.72787881]]])

 9. Write a NumPy program to convert a list of numeric values into a
one-dimensional NumPy array

In [42]:
l = [4,5,6,7,8,9,2,4,6,4]
type(l)

list

In [43]:
a = np.array(l)
type(a)

numpy.ndarray

In [44]:
a

array([4, 5, 6, 7, 8, 9, 2, 4, 6, 4])

10. Write a NumPy program to create a 4x4 matrix with values ranging from 7
to 15.

In [45]:
a4 = np.linspace(7,15,16).reshape((4,4))
a4


array([[ 7.        ,  7.53333333,  8.06666667,  8.6       ],
       [ 9.13333333,  9.66666667, 10.2       , 10.73333333],
       [11.26666667, 11.8       , 12.33333333, 12.86666667],
       [13.4       , 13.93333333, 14.46666667, 15.        ]])

In [46]:
np.shape(a4)

(4, 4)

11. Write a NumPy program to create a null vector of size 10 and update the
sixth value to 11.


In [54]:
n_vector= np.zeros(10)
n_vector[5] = 11
n_vector

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

12. Write a NumPy program to create a 2d array with 1 on the border and 0
inside.


In [50]:
a2 = np.zeros(10)

In [53]:
a2[0] = 1
a2[-1] = 1

arr_2d= np.array([a2])
arr_2d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

13. Write a NumPy program to convert the values of Centigrade degrees into
Fahrenheit degrees and vice versa. Values are stored into a NumPy array.


In [59]:
values_in_C = np.array([10,20,30,40])
values_in_F = np.array([80,98,104,145])
C_to_F = 1.8*values_in_C + 32
F_to_C = (values_in_F-32)/1.8


In [60]:
print("Values Centigrade to Fahrenheit: ",C_to_F)
print("Values Fahrenheit to centigrade: ",F_to_C)

Values Centigrade to Fahrenheit:  [ 50.  68.  86. 104.]
Values Fahrenheit to centigrade:  [26.66666667 36.66666667 40.         62.77777778]


14. Write a NumPy program to create an array of ones and an array of zeros

In [61]:
ones_arr = np.ones(10)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
zeros_arr = np.zeros(10)
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

15. Write a NumPy program to create a new shape to an array without
changing its data.

In [63]:
a = np.arange(15,35,2)

In [64]:
a

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [65]:
np.shape(a)

(10,)

In [66]:
new_arr = a.reshape((5,2))
new_arr

array([[15, 17],
       [19, 21],
       [23, 25],
       [27, 29],
       [31, 33]])

In [67]:
np.shape(new_arr)

(5, 2)

 16. Write a NumPy program to create a new array of 3*5, filled with 2.

In [71]:
a = np.array([2,2,2,2,2,2,2,2,2,2,2,2,2,2,2])
np.shape(a)

(15,)

In [72]:
a = a.reshape((3,5))
a

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [73]:
np.shape(a)

(3, 5)

17. Write a NumPy program to create a 3-D array with ones on a diagonal
and zeros elsewhere

In [78]:
a3 = np.eye(3,3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.shape(a3)

(3, 3)

In [80]:
a3 = a3.reshape(1,3,3)
np.shape(a3)

(1, 3, 3)

In [81]:
a3

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

18. Write a NumPy program to create a 1-D array of 20 element spaced
evenly on a log scale between 2. and 5., exclusive.


In [82]:
a = np.linspace(2,5,20)
a

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

19. Write a NumPy program (using NumPy) to sum of all the multiples of 3
or 5 below 100

In [91]:
arr = np.array([6,5,4,12,15,20,24,56,55,48,63,65,66,145,25])
def sum_():
    sum_ = 0
    
    for i in arr:
        
        if i%3==0 or i%5==0 and i<100:
            sum_ = sum_+i
    return sum_
print(sum_())

404
