In [1]:
import numpy as np

In [2]:
import csv

In [3]:
data = []

In [4]:
with open(r"C:\Users\HP\Desktop\Data-LB\New folder\MER_T07_02A-2020-02-03.csv",'r') as csvfile:
    filereader = csv.reader(csvfile,delimiter=',')
    for row in filereader:
        data.append(row)
        

In [5]:
data

[['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
 ['CLETPUS',
  '194913',
  '135451.32',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195013',
  '154519.994',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195113',
  '185203.657',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195213',
  '195436.666',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195313',
  '218846.325',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195413',
  '239145.966',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '195513',
  '301362.698',
  '1',
  'Electricity Net Generation From Coal, All Sectors',
  'Million Kilowatthours'],
 ['CLETPUS',
  '

In [6]:
data = np.array(data)

In [7]:
data

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

# 1. Explore the important attributes like dimension,shape, data type etc, of the array formed above

In [8]:
data.ndim

2

In [9]:
data.shape

(8217, 6)

In [10]:
data.dtype.type

numpy.str_

# 2. Print the data contained in the first 10 rows of the 4th column.


In [11]:
data[0:10]

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195213', '195436.666', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195313', '218846.325', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195413', '239145.966', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195513', '301362.698', '1',
        'Electricity 

In [12]:
data[-5:]

array([['ELETPUS', '201906', '351342.905', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201907', '411583.828', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [13]:
np.vstack((data[0:5],data[-5:]))

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195213', '195436.666', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201906', '351342.905', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201907', '411583.828', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
     

In [14]:
##Print the data contained in the first 10 rows of the 4th column
data[0:10,3:4]

array([['Column_Order'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1']], dtype='<U80')

# 3. Which row serves as the headers/titles for all the columns.

In [15]:
#first row
data[0:1]

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit']],
      dtype='<U80')

# 4. Print the data contained in column 2 and 3 from row 1 till row 20

In [16]:
data[0:20,1:3]

array([['YYYYMM', 'Value'],
       ['194913', '135451.32'],
       ['195013', '154519.994'],
       ['195113', '185203.657'],
       ['195213', '195436.666'],
       ['195313', '218846.325'],
       ['195413', '239145.966'],
       ['195513', '301362.698'],
       ['195613', '338503.484'],
       ['195713', '346386.207'],
       ['195813', '344365.781'],
       ['195913', '378424.21'],
       ['196013', '403067.357'],
       ['196113', '421870.669'],
       ['196213', '450249.238'],
       ['196313', '493926.719'],
       ['196413', '526230.019'],
       ['196513', '570925.951'],
       ['196613', '613474.8'],
       ['196713', '630483.363']], dtype='<U80')

# 5. Print the data present in only the first three and the last three rows of all the columns in a single output.


In [17]:
np.vstack((data[0:3],data[-3:]))


array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

# 6. Sort the data on the basis of net amount of electricity generated irrespective of the source

In [18]:
value = data[1:,2]


In [19]:
cndn_of_slcn = (data[:,2]!="Not Available")
cndn_of_slcn.shape

(8217,)

In [20]:
a = data[cndn_of_slcn]
a

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [21]:
a.shape

(7387, 6)

In [22]:
e = a[1:,2].astype(float)
e

array([135451.32 , 154519.994, 185203.657, ..., 401363.186, 359300.603,
       321921.812])

In [23]:
e = np.sort(e)
e

array([  -8823.445,   -8742.928,   -8535.065, ..., 4125059.9  ,
       4156744.724, 4174397.655])

# 7. Find the total amount of electricity generated using coal and nuclear between 1949-1990.( In this dataset, rows containing monthly data express date in the format 'YYYYMM'. Rows containing annual data express the date in the format 'YYYY13'.)

In [24]:
data

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [25]:
b = a[1:]

In [26]:
time = a[1:,1]

In [27]:
time = time.astype(int)


In [28]:
cond_time = np.mod(time,100)==13
cond_time

array([ True,  True,  True, ..., False, False, False])

In [29]:
cond_time.shape

(7386,)

In [30]:
t = b[cond_time]
t

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201613', '4076674.984', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201713', '4034270.522', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201813', '4174397.655', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [31]:
t.shape


(728, 6)

In [32]:
cond_timelimit = t[0:,1].astype(int)<=199013

In [33]:
t = t[cond_timelimit]
t

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '198813', '2707411.178', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '198913', '2967146.087', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '199013', '3037827.337', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [34]:
t.shape

(364, 6)

In [35]:
source_cndn = t[:,4]=='Electricity Net Generation From Coal, All Sectors'

In [36]:
energy_coal = t[source_cndn]
energy_coal.shape

(42, 6)

In [37]:
source_cndn_nuc = t[:,4]=='Electricity Net Generation From Nuclear Electric Power, All Sectors'

In [38]:
energy_nuc = t[source_cndn_nuc]
energy_nuc.shape

(42, 6)

In [39]:
final_energy = np.vstack((energy_coal,energy_nuc))
final_energy

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195213', '195436.666', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195313', '218846.325', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195413', '239145.966', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195513', '301362.698', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],


In [40]:
np.sum(final_energy[:,2].astype(float))

37990978.569000006

# 8. Print all the unique sources of Energy generation present in the dataset.


In [41]:
np.unique(data[:,4:5])

array(['Description', 'Electricity Net Generation From Coal, All Sectors',
       'Electricity Net Generation From Conventional Hydroelectric Power, All Sectors',
       'Electricity Net Generation From Geothermal, All Sectors',
       'Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors',
       'Electricity Net Generation From Natural Gas, All Sectors',
       'Electricity Net Generation From Nuclear Electric Power, All Sectors',
       'Electricity Net Generation From Other Gases, All Sectors',
       'Electricity Net Generation From Petroleum, All Sectors',
       'Electricity Net Generation From Solar, All Sectors',
       'Electricity Net Generation From Waste, All Sectors',
       'Electricity Net Generation From Wind, All Sectors',
       'Electricity Net Generation From Wood, All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors'],
      dtype='<U80')

# 9. Print all the details(annual) where the energy source is Wind Energy. Use the concept of masking to filter the data.

In [42]:
energy = a[1:]
energy

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [43]:
e_1 = energy[:,1].astype(int)
e_1

array([194913, 195013, 195113, ..., 201908, 201909, 201910])

In [44]:
cond_time = np.mod(e_1,100)==13
cond_time


array([ True,  True,  True, ..., False, False, False])

In [45]:
e_2 = energy[cond_time]
e_2

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201613', '4076674.984', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201713', '4034270.522', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201813', '4174397.655', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [46]:
cond_wind = e_2[:,4]=='Electricity Net Generation From Wind, All Sectors'

In [47]:
annual_detail = e_2[cond_wind]
annual_detail.shape

(36, 6)

In [48]:
annual_detail

array([['WYETPUS', '198313', '2.668', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198413', '6.49', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198513', '5.762', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198613', '4.189', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198713', '3.541', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198813', '0.871', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198913', '2112.043', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '19901

# 10. Print the Total Energy generated in the USA till date

In [49]:
totatl_energy = a[1:,2]

In [50]:
totatl_energy.shape


(7386,)

In [51]:
np.sum(totatl_energy.astype(float))

642969289.517

# 11. Print the average annual energy generated from wind in the USA and also the standard deviation present in the energy generation.


In [52]:
wind_energy = annual_detail
wind_energy.shape

(36, 6)

In [53]:
np.sum(wind_energy[:,2].astype(float))

1940339.685

In [74]:
avg_wind_energy = np.mean(wind_energy[:,2].astype(float))
avg_wind_energy

53898.324583333335

In [55]:
##standard deviation
np.std(wind_energy[:,2].astype(float))

81322.74833843806

# 12. What and when was the maximum annual energy generated?


In [56]:
energy

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [57]:
cond_max = np.argmax(energy[:,2].astype(float))
cond_max

7375

In [58]:
max_energy_date = energy[cond_max]
max_energy_date[1]

'201813'

In [59]:
max_energy = np.max(energy[:,2].astype(float))
max_energy

4174397.655