In [1]:
import numpy as np
import csv

# 1. Represent the data in the given sheet into an appropriate NumPy array

1. read the csv file

2. append in the list

3. convert the list into NumPy Array

4. delete first two row

5. Fill the correct value at blank space

In [2]:
data = []

In [3]:
with open(r"C:\Users\HP\Desktop\Data-LB\New folder\SampleTemperature Sheet - mysheet.csv",'r') as csvfile:
    filereader = csv.reader(csvfile,delimiter=',')
    for row in filereader:
        data.append(row)
        

In [4]:
data = np.array(data)
data

array([['Temprature Sheet', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
       ['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['', 'Week 2', '13', '23', '13', '29', '8', '22', '-13', '32',
        '6', '21', '14', '23', '11', '28'],
       ['', 'Week 3', '6', '28', '14', '21', '9', '32', '8', '28', '13',
        '30', '6', '31', '6', '23'],
       ['', 'Week 4', '6', '23', '8', '23', '14', '24', '6', '29', '13',
        '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '1

In [5]:
data = np.delete(data,0,axis=0)

In [6]:
data = np.delete(data,0,axis=0)

In [7]:
data[0:3]

array([['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27']], dtype='<U16')

In [8]:
d1 = data[2:,:]
d1

array([['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['', 'Week 2', '13', '23', '13', '29', '8', '22', '-13', '32',
        '6', '21', '14', '23', '11', '28'],
       ['', 'Week 3', '6', '28', '14', '21', '9', '32', '8', '28', '13',
        '30', '6', '31', '6', '23'],
       ['', 'Week 4', '6', '23', '8', '23', '14', '24', '6', '29', '13',
        '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['', 'Week 2', '9', '30', '15', '26', '9', '27', '14', '31', '8',
        '22', '10', '26', '12', '28'],
       ['', 'Week 3', '6', '28', '12', '31', '14', '27', '9', '32', '7',
        '23', '11', '32', '7', '23'],
       ['', 'Week 4', '7', '28', '15', '29', '11', '22', '14', '21',
        '12', '27', '12', '31', '14', '25'],
       ['January', 'Week 1', '5', '22', '8', '21', '8', '20', '7', '19',
        '8', 

In [9]:
#condition for blank space in column 1
c = d1[:,0]==''
c

array([False,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True])

In [10]:
#Filling of column 1 with months name
d1[1:4,0:1] = 'November'
d1[5:8,0:1] = 'December'
d1[9:12,0:1]= 'January'
d1[13:16,0:1] = 'February'

In [11]:
d1

array([['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['December', 'Week 2', '9', '30', '15', '26', '9', '27', '14',
        '31', '8', '22', '10', '26', '12', '28'],
       ['December', 'Week 3', '6', '28', '12', '31', '14', '27', '9',
        '32', '7', '23', '11', '32', '7', '23'],
       ['December', 'Week 4', '7', '28', '15', '29', '11', '22', '14',
        '21', '12', '27', '12', '31', '14', '25'],
       ['January', 'Week 1', '5', '22'

In [12]:
#vertical stacking to add tilte
d2 = np.vstack((data[0:2,:],d1))
d2

array([['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['December', 'Week 2', '9', '30', '15', '26', '9', 

In [13]:
#condition for blank space in row 1
c2 = data[0:1,:] ==''
c2

array([[False, False, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True]])

In [14]:
#Filling of row 1 with day name
data[0:1,3:4] = 'Monday'
data[0:1,5:6] = 'Tuesday'
data[0:1,7:8] = 'Wednesday'
data[0:1,9:10] = 'Thursday'
data[0:1,11:12] = 'Friday'
data[0:1,13:14] = 'Saturday'
data[0:1,15:16] = 'Sunday'

In [15]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],


# 2. Write the dimensions and shape of the NumPy array that you have created.
1. Use ndim function to find the dimension of array.

2. use the shape method to find the shape of array.

In [16]:
#Dimmension
dim = np.ndim(data)
dim

2

In [17]:
#shape of data
data.shape

(18, 16)

# 3. Print the daily temperatures for the first week of each month.
1. make a condition, that is true for Week 1 only.

2. Find the data for true condition only.

In [18]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27']], dtype='<U16')

In [19]:
#condtion for Week 1
cond_week1 = data[:,1]=='Week 1'
cond_week1

array([False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False])

In [20]:
data_1 = data[cond_week1]
data_1

array([['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['January', 'Week 1', '5', '22', '8', '21', '8', '20', '7', '19',
        '8', '22', '2', '7', '18', '4'],
       ['February', 'Week 1', '8', '22', '7', '19', '-10', '18', '11',
        '19', '12', '20', '12', '71', '21', '12']], dtype='<U16')

In [21]:
#Vertical stacking
week1_temp = np.vstack((data[0:2,:],data_1))
week1_temp

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['January', 'Week 1', '5', '22', '8', '21', '8', '20', '7', '19',
        '8', '22', '2', '7', '18', '4'],
       ['February', 'Week 1', '8', '22', '7', '19', '-10', '18', '11',
        '19', '12', '20', '12', '71', '21', '12']], dtype='<U16')

# 4. Print the temperatures for Tuesday of each month.
1. slicing of data.

2. Horizontal stacking.

In [22]:
tuesday_temp = data[:,4:6]
tuesday_temp

array([['Tuesday', 'Tuesday'],
       ['Min Temp', 'Max Temp'],
       ['10', '20'],
       ['13', '29'],
       ['14', '21'],
       ['8', '23'],
       ['14', '25'],
       ['15', '26'],
       ['12', '31'],
       ['15', '29'],
       ['8', '21'],
       ['6', '20'],
       ['7', '18'],
       ['2', '18'],
       ['7', '19'],
       ['10', '20'],
       ['11', '19'],
       ['7', '20']], dtype='<U16')

In [23]:
np.hstack((data[:,0:2],tuesday_temp))

array([['Month', 'Week', 'Tuesday', 'Tuesday'],
       ['', '', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '10', '20'],
       ['November', 'Week 2', '13', '29'],
       ['November', 'Week 3', '14', '21'],
       ['November', 'Week 4', '8', '23'],
       ['December', 'Week 1', '14', '25'],
       ['December', 'Week 2', '15', '26'],
       ['December', 'Week 3', '12', '31'],
       ['December', 'Week 4', '15', '29'],
       ['January', 'Week 1', '8', '21'],
       ['January', 'Week 2', '6', '20'],
       ['January', 'Week 3', '7', '18'],
       ['January', 'Week 4', '2', '18'],
       ['February', 'Week 1', '7', '19'],
       ['February', 'Week 2', '10', '20'],
       ['February', 'Week 3', '11', '19'],
       ['February', 'Week 4', '7', '20']], dtype='<U16')

# 5. Print only the maximum temperature for all the weekdays of Dec and Feb.

1. Find maximum temperature for all months and weeks by slicing and stacking

2. mask for dec and feb


In [24]:
data[1:2]

array([['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U16')

In [25]:
max_temp = np.hstack((data[:,0:2],data[:,3::2]))
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '20', '20', '30', '24', '29', '21', '27'],
       ['November', 'Week 2', '23', '29', '22', '32', '21', '23', '28'],
       ['November', 'Week 3', '28', '21', '32', '28', '30', '31', '23'],
       ['November', 'Week 4', '23', '23', '24', '29', '25', '24', '27'],
       ['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '20', '19', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '22', '21', '3', '5'],
       ['January', 'Week 3', '21', '18', '21', '19', '1

In [26]:
#condition for december temperature

cond_dec =max_temp[:,0]=='December' 
dec_temp = max_temp[cond_dec]

In [27]:
#Condition for february temperature

cond_feb = max_temp[0:,0]== 'February'
feb_temp = max_temp[cond_feb]

In [28]:
#Vertical stacking for title, december and february

np.vstack(((max_temp[0:2,:],dec_temp,feb_temp)))

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['February', 'Week 1', '22', '19', '18', '19', '20', '71', '12'],
       ['February', 'Week 2', '19', '20', '18', '18', '22', '11', '7'],
       ['February', 'Week 3', '22', '19', '21', '21', '19', '10', '10'],
       ['February', 'Week 4', '21', '20', '21', '18', '20', '7', '9']],
      dtype='<U16')

# 6. Print all the days along with the week number in November when the minimum temperature was less than 8 degrees.

In [29]:
#creat an array for min temp
min_temp = np.hstack((data[:,0:2],data[:,2::2]))
min_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp', 'Min Temp'],
       ['November', 'Week 1', '11', '10', '9', '14', '6', '12', '12'],
       ['November', 'Week 2', '13', '13', '8', '-13', '6', '14', '11'],
       ['November', 'Week 3', '6', '14', '9', '8', '13', '6', '6'],
       ['November', 'Week 4', '6', '8', '14', '6', '13', '12', '11'],
       ['December', 'Week 1', '11', '14', '7', '9', '9', '11', '11'],
       ['December', 'Week 2', '9', '15', '9', '14', '8', '10', '12'],
       ['December', 'Week 3', '6', '12', '14', '9', '7', '11', '7'],
       ['December', 'Week 4', '7', '15', '11', '14', '12', '12', '14'],
       ['January', 'Week 1', '5', '8', '8', '7', '8', '2', '18'],
       ['January', 'Week 2', '4', '6', '6', '4', '4', '3', '20'],
       ['January', 'Week 3', '5', '7', '8', '4', '4', '3', '18'],
       ['January', 

In [30]:
#mask for nov
cond_nov = min_temp[:,0]=='November'
cond_nov

array([False, False,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [31]:
#min_temp for Nov
min_temp_nov = min_temp[cond_nov]
min_temp_nov

array([['November', 'Week 1', '11', '10', '9', '14', '6', '12', '12'],
       ['November', 'Week 2', '13', '13', '8', '-13', '6', '14', '11'],
       ['November', 'Week 3', '6', '14', '9', '8', '13', '6', '6'],
       ['November', 'Week 4', '6', '8', '14', '6', '13', '12', '11']],
      dtype='<U16')

In [32]:
#data type change into int
t = min_temp_nov[:,2:].astype(int)
t

array([[ 11,  10,   9,  14,   6,  12,  12],
       [ 13,  13,   8, -13,   6,  14,  11],
       [  6,  14,   9,   8,  13,   6,   6],
       [  6,   8,  14,   6,  13,  12,  11]])

In [33]:
#Week1 data in 1D array
week_1 = t[0:1,:].reshape(7,)
week_1

array([11, 10,  9, 14,  6, 12, 12])

In [34]:
#Week2 data in 1D array
week_2 = t[1:2,:].reshape(7,)
week_2

array([ 13,  13,   8, -13,   6,  14,  11])

In [35]:
#Week3 data in 1D array
week_3 = t[2:3,:].reshape(7,)
week_3

array([ 6, 14,  9,  8, 13,  6,  6])

In [36]:
#Week4 data in 1D array
week_4 = t[3:4,:].reshape(7,)
week_4

array([ 6,  8, 14,  6, 13, 12, 11])

In [37]:
#Condition for check where temp <8 for week1
#write temp<8 in a list
w1 = []
for n in week_1:
    if n<8:
        w1.append(n)
    else:
        w1.append('')
print(w1)

['', '', '', '', 6, '', '']


In [38]:
#Condition for check where temp <8 for week2
#write temp<8 in a list
w2 = []
for n in week_2:
    if n<8:
        w2.append(n)
    else:
        w2.append('')
print(w2)

['', '', '', -13, 6, '', '']


In [39]:
#Condition for check where temp <8 for week3
#write temp<8 in a list
w3 = []
for n in week_3:
    if n<8:
        w3.append(n)
    else:
        w3.append('')
print(w3)

[6, '', '', '', '', 6, 6]


In [40]:
#Condition for check where temp <8 for week4
#write temp<8 in a list
w4 = []
for n in week_4:
    if n<8:
        w4.append(n)
    else:
        w4.append('')
print(w4)

[6, '', '', 6, '', '', '']


In [41]:
#list to array conversion
#1D to 2D array conversion
w1 = np.array(w1).reshape(1,7)
w2 = np.array(w2).reshape(1,7)
w3 = np.array(w3).reshape(1,7)
w4 = np.array(w4).reshape(1,7)

In [42]:
# Vertical stcking of Week1, Week2, Week3 and Week4
Nov_temp = np.vstack((((w1,w2,w3,w4))))
Nov_temp

array([['', '', '', '', '6', '', ''],
       ['', '', '', '-13', '6', '', ''],
       ['6', '', '', '', '', '6', '6'],
       ['6', '', '', '6', '', '', '']], dtype='<U11')

In [43]:
#Horizonbtal stacking
temp_lesser_8 = np.hstack((min_temp_nov[:,0:2],Nov_temp))

In [44]:
temp_lesser_8

array([['November', 'Week 1', '', '', '', '', '6', '', ''],
       ['November', 'Week 2', '', '', '', '-13', '6', '', ''],
       ['November', 'Week 3', '6', '', '', '', '', '6', '6'],
       ['November', 'Week 4', '6', '', '', '6', '', '', '']], dtype='<U16')

# 7. Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.


In [45]:
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '20', '20', '30', '24', '29', '21', '27'],
       ['November', 'Week 2', '23', '29', '22', '32', '21', '23', '28'],
       ['November', 'Week 3', '28', '21', '32', '28', '30', '31', '23'],
       ['November', 'Week 4', '23', '23', '24', '29', '25', '24', '27'],
       ['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '20', '19', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '22', '21', '3', '5'],
       ['January', 'Week 3', '21', '18', '21', '19', '1

In [46]:
cond_dec = max_temp[:,0]=='December'

In [47]:
cond_jan = max_temp[:,0]=='January'

In [48]:
dec_jan = np.vstack((max_temp[cond_dec],max_temp[cond_jan]))

In [49]:
dec_jan

array([['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '20', '19', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '22', '21', '3', '5'],
       ['January', 'Week 3', '21', '18', '21', '19', '18', '7', '4'],
       ['January', 'Week 4', '19', '18', '20', '22', '19', '4', '8']],
      dtype='<U16')

In [50]:
dec_w1 = dec_jan[0:1,2:].reshape(7,).astype(int)
dec_w1

array([25, 25, 20, 28, 23, 23, 30])

In [51]:
dec_w2 = dec_jan[1:2,2:].reshape(7,).astype(int)
dec_w3 = dec_jan[2:3,2:].reshape(7,).astype(int)
dec_w4 = dec_jan[3:4,2:].reshape(7,).astype(int)

In [52]:
dec_w4

array([28, 29, 22, 21, 27, 31, 25])

In [53]:
jan_w1 = dec_jan[4:5,2:].reshape(7,).astype(int)
jan_w2 = dec_jan[5:6,2:].reshape(7,).astype(int)
jan_w3 = dec_jan[6:7,2:].reshape(7,).astype(int)
jan_w4 = dec_jan[7:8,2:].reshape(7,).astype(int)

In [54]:
jan_w1

array([22, 21, 20, 19, 22,  7,  4])

In [55]:
d_w1 = []
for i in dec_w1:
    if i>20:
        d_w1.append(i)
    else:
        d_w1.append('')
print(d_w1 )

[25, 25, '', 28, 23, 23, 30]


In [56]:
d_w2 = []
for i in dec_w2:
    if i>20:
        d_w2.append(i)
    else:
        d_w2.append('')
print(d_w2)

[30, 26, 27, 31, 22, 26, 28]


In [57]:
d_w3 = []
for i in dec_w3:
    if i>20:
        d_w3.append(i)
    else:
        d_w3.append('')
print(d_w3)

[28, 31, 27, 32, 23, 32, 23]


In [58]:
d_w4= []
for i in dec_w4:
    if i>20:
        d_w4.append(i)
    else:
        d_w4.append('')
print(d_w4)

[28, 29, 22, 21, 27, 31, 25]


In [59]:
j_w1= []
for i in jan_w1:
    if i>20:
        j_w1.append(i)
    else:
        j_w1.append('')
print(j_w1)

j_w2= []
for i in jan_w2:
    if i>20:
        j_w2.append(i)
    else:
        j_w2.append('')
print(j_w2)

j_w3= []
for i in jan_w3:
    if i>20:
        j_w3.append(i)
    else:
        j_w3.append('')
print(j_w3)

j_w4= []
for i in jan_w4:
    if i>20:
        j_w4.append(i)
    else:
        j_w4.append('')
print(j_w4)

[22, 21, '', '', 22, '', '']
[22, '', 21, 22, 21, '', '']
[21, '', 21, '', '', '', '']
['', '', '', 22, '', '', '']


In [60]:
d_w1 = np.array(d_w1).reshape(1,7)
d_w2 = np.array(d_w2).reshape(1,7)
d_w3 = np.array(d_w3).reshape(1,7)
d_w4 = np.array(d_w4).reshape(1,7)

In [61]:
d_w1

array([['25', '25', '', '28', '23', '23', '30']], dtype='<U11')

In [62]:
j_w1 = np.array(j_w1).reshape(1,7)
j_w2 = np.array(j_w2).reshape(1,7)
j_w3 = np.array(j_w3).reshape(1,7)
j_w4 = np.array(j_w4).reshape(1,7)

In [63]:
j_w1

array([['22', '21', '', '', '22', '', '']], dtype='<U11')

In [64]:
temp = np.vstack((((((((d_w1,d_w2,d_w3,d_w4,j_w1,j_w2,j_w3,j_w4))))))))
temp

array([['25', '25', '', '28', '23', '23', '30'],
       ['30', '26', '27', '31', '22', '26', '28'],
       ['28', '31', '27', '32', '23', '32', '23'],
       ['28', '29', '22', '21', '27', '31', '25'],
       ['22', '21', '', '', '22', '', ''],
       ['22', '', '21', '22', '21', '', ''],
       ['21', '', '21', '', '', '', ''],
       ['', '', '', '22', '', '', '']], dtype='<U11')

In [65]:
temp_greater_20 = np.hstack((dec_jan[:,0:2],temp))

In [66]:
temp_greater_20

array([['December', 'Week 1', '25', '25', '', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '', '', '22', '', ''],
       ['January', 'Week 2', '22', '', '21', '22', '21', '', ''],
       ['January', 'Week 3', '21', '', '21', '', '', '', ''],
       ['January', 'Week 4', '', '', '', '22', '', '', '']], dtype='<U16')

# 8. Check if there are any absurd values present in the dataset(like some temp which should not be present in the data)


In [67]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27']], dtype='<U16')

In [68]:
d1 = data[2:,2:]
d1

array([['11', '20', '10', '20', '9', '30', '14', '24', '6', '29', '12',
        '21', '12', '27'],
       ['13', '23', '13', '29', '8', '22', '-13', '32', '6', '21', '14',
        '23', '11', '28'],
       ['6', '28', '14', '21', '9', '32', '8', '28', '13', '30', '6',
        '31', '6', '23'],
       ['6', '23', '8', '23', '14', '24', '6', '29', '13', '25', '12',
        '24', '11', '27'],
       ['11', '25', '14', '25', '7', '20', '9', '28', '9', '23', '11',
        '23', '11', '30'],
       ['9', '30', '15', '26', '9', '27', '14', '31', '8', '22', '10',
        '26', '12', '28'],
       ['6', '28', '12', '31', '14', '27', '9', '32', '7', '23', '11',
        '32', '7', '23'],
       ['7', '28', '15', '29', '11', '22', '14', '21', '12', '27', '12',
        '31', '14', '25'],
       ['5', '22', '8', '21', '8', '20', '7', '19', '8', '22', '2', '7',
        '18', '4'],
       ['4', '22', '6', '20', '6', '21', '4', '22', '4', '21', '3', '3',
        '20', '5'],
       ['5', '21', '7', '18'

In [69]:
cond = d1==''

In [70]:
d1[cond]

array([], dtype='<U16')

All temperature values are present

................................................

# 10. Find and print the indexes of all the outlier(unusual) values present in the above dataset.

In [71]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],


In [72]:
temp_1 = data[2:,2:].astype(int)

In [73]:
temp_1.shape

(16, 14)

In [74]:
temp_1 = temp_1.reshape(16*14,)

In [75]:
temp_1

array([ 11,  20,  10,  20,   9,  30,  14,  24,   6,  29,  12,  21,  12,
        27,  13,  23,  13,  29,   8,  22, -13,  32,   6,  21,  14,  23,
        11,  28,   6,  28,  14,  21,   9,  32,   8,  28,  13,  30,   6,
        31,   6,  23,   6,  23,   8,  23,  14,  24,   6,  29,  13,  25,
        12,  24,  11,  27,  11,  25,  14,  25,   7,  20,   9,  28,   9,
        23,  11,  23,  11,  30,   9,  30,  15,  26,   9,  27,  14,  31,
         8,  22,  10,  26,  12,  28,   6,  28,  12,  31,  14,  27,   9,
        32,   7,  23,  11,  32,   7,  23,   7,  28,  15,  29,  11,  22,
        14,  21,  12,  27,  12,  31,  14,  25,   5,  22,   8,  21,   8,
        20,   7,  19,   8,  22,   2,   7,  18,   4,   4,  22,   6,  20,
         6,  21,   4,  22,   4,  21,   3,   3,  20,   5,   5,  21,   7,
        18,   8,  21,   4,  19,   4,  18,   3,   7,  18,   4,   6,  19,
         2,  18,   7,  20,   8,  22,   8,  19,   7,   4,  20,   8,   8,
        22,   7,  19, -10,  18,  11,  19,  12,  20,  12,  71,  2

In [76]:
sort_temp_1 = np.sort(temp_1)
sort_temp_1

array([-13, -10,   2,   2,   3,   3,   3,   4,   4,   4,   4,   4,   4,
         4,   4,   5,   5,   5,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   9,   9,   9,   9,   9,   9,
         9,   9,   9,   9,  10,  10,  10,  10,  10,  10,  10,  11,  11,
        11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,
        12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,
        13,  13,  13,  13,  14,  14,  14,  14,  14,  14,  14,  14,  14,
        15,  15,  18,  18,  18,  18,  18,  18,  18,  18,  18,  19,  19,
        19,  19,  19,  19,  19,  19,  19,  19,  19,  20,  20,  20,  20,
        20,  20,  20,  20,  20,  20,  20,  20,  21,  21,  21,  21,  21,
        21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  23,  23,  23,  2

In [77]:
sort_temp_1.shape

(224,)

In [78]:
mean = round(np.mean(temp_1),3)
mean

15.647

In [79]:
std = np.std(temp_1)
std

9.178570342898768

In [80]:
q1 = np.median(sort_temp_1[0:112])
q3 = np.median(sort_temp_1[112:])
print(q1,q3)

8.0 22.0


In [81]:
iqr = q3-q1
iqr

14.0

In [82]:
b = []
for i in temp_1:
    if i>q1-1.5*iqr and i<q3+1.5*iqr:
        b.append(i)
    else:
        b.append('outlier')
print(b)        

[11, 20, 10, 20, 9, 30, 14, 24, 6, 29, 12, 21, 12, 27, 13, 23, 13, 29, 8, 22, 'outlier', 32, 6, 21, 14, 23, 11, 28, 6, 28, 14, 21, 9, 32, 8, 28, 13, 30, 6, 31, 6, 23, 6, 23, 8, 23, 14, 24, 6, 29, 13, 25, 12, 24, 11, 27, 11, 25, 14, 25, 7, 20, 9, 28, 9, 23, 11, 23, 11, 30, 9, 30, 15, 26, 9, 27, 14, 31, 8, 22, 10, 26, 12, 28, 6, 28, 12, 31, 14, 27, 9, 32, 7, 23, 11, 32, 7, 23, 7, 28, 15, 29, 11, 22, 14, 21, 12, 27, 12, 31, 14, 25, 5, 22, 8, 21, 8, 20, 7, 19, 8, 22, 2, 7, 18, 4, 4, 22, 6, 20, 6, 21, 4, 22, 4, 21, 3, 3, 20, 5, 5, 21, 7, 18, 8, 21, 4, 19, 4, 18, 3, 7, 18, 4, 6, 19, 2, 18, 7, 20, 8, 22, 8, 19, 7, 4, 20, 8, 8, 22, 7, 19, -10, 18, 11, 19, 12, 20, 12, 'outlier', 21, 12, 8, 19, 10, 20, 12, 18, 10, 18, 10, 22, 8, 11, 19, 7, 9, 22, 11, 19, 7, 21, 11, 21, 9, 19, 7, 10, 19, 10, 11, 21, 7, 20, 11, 21, 12, 18, 11, 20, 12, 7, 21, 9]


In [83]:
temp_outliers = np.array(b).reshape(16,14)
temp_outliers

array([['11', '20', '10', '20', '9', '30', '14', '24', '6', '29', '12',
        '21', '12', '27'],
       ['13', '23', '13', '29', '8', '22', 'outlier', '32', '6', '21',
        '14', '23', '11', '28'],
       ['6', '28', '14', '21', '9', '32', '8', '28', '13', '30', '6',
        '31', '6', '23'],
       ['6', '23', '8', '23', '14', '24', '6', '29', '13', '25', '12',
        '24', '11', '27'],
       ['11', '25', '14', '25', '7', '20', '9', '28', '9', '23', '11',
        '23', '11', '30'],
       ['9', '30', '15', '26', '9', '27', '14', '31', '8', '22', '10',
        '26', '12', '28'],
       ['6', '28', '12', '31', '14', '27', '9', '32', '7', '23', '11',
        '32', '7', '23'],
       ['7', '28', '15', '29', '11', '22', '14', '21', '12', '27', '12',
        '31', '14', '25'],
       ['5', '22', '8', '21', '8', '20', '7', '19', '8', '22', '2', '7',
        '18', '4'],
       ['4', '22', '6', '20', '6', '21', '4', '22', '4', '21', '3', '3',
        '20', '5'],
       ['5', '21', '7', 

# 11.Replace the outliers with an appropriate value.


In [84]:
k = []
for i in b:
    if i!='outlier':
        k.append(i)
    else:
        k.append(mean)
print(k)

[11, 20, 10, 20, 9, 30, 14, 24, 6, 29, 12, 21, 12, 27, 13, 23, 13, 29, 8, 22, 15.647, 32, 6, 21, 14, 23, 11, 28, 6, 28, 14, 21, 9, 32, 8, 28, 13, 30, 6, 31, 6, 23, 6, 23, 8, 23, 14, 24, 6, 29, 13, 25, 12, 24, 11, 27, 11, 25, 14, 25, 7, 20, 9, 28, 9, 23, 11, 23, 11, 30, 9, 30, 15, 26, 9, 27, 14, 31, 8, 22, 10, 26, 12, 28, 6, 28, 12, 31, 14, 27, 9, 32, 7, 23, 11, 32, 7, 23, 7, 28, 15, 29, 11, 22, 14, 21, 12, 27, 12, 31, 14, 25, 5, 22, 8, 21, 8, 20, 7, 19, 8, 22, 2, 7, 18, 4, 4, 22, 6, 20, 6, 21, 4, 22, 4, 21, 3, 3, 20, 5, 5, 21, 7, 18, 8, 21, 4, 19, 4, 18, 3, 7, 18, 4, 6, 19, 2, 18, 7, 20, 8, 22, 8, 19, 7, 4, 20, 8, 8, 22, 7, 19, -10, 18, 11, 19, 12, 20, 12, 15.647, 21, 12, 8, 19, 10, 20, 12, 18, 10, 18, 10, 22, 8, 11, 19, 7, 9, 22, 11, 19, 7, 21, 11, 21, 9, 19, 7, 10, 19, 10, 11, 21, 7, 20, 11, 21, 12, 18, 11, 20, 12, 7, 21, 9]


In [85]:
out_re_array = np.array(k).reshape(16,14)
out_re_array

array([[ 11.   ,  20.   ,  10.   ,  20.   ,   9.   ,  30.   ,  14.   ,
         24.   ,   6.   ,  29.   ,  12.   ,  21.   ,  12.   ,  27.   ],
       [ 13.   ,  23.   ,  13.   ,  29.   ,   8.   ,  22.   ,  15.647,
         32.   ,   6.   ,  21.   ,  14.   ,  23.   ,  11.   ,  28.   ],
       [  6.   ,  28.   ,  14.   ,  21.   ,   9.   ,  32.   ,   8.   ,
         28.   ,  13.   ,  30.   ,   6.   ,  31.   ,   6.   ,  23.   ],
       [  6.   ,  23.   ,   8.   ,  23.   ,  14.   ,  24.   ,   6.   ,
         29.   ,  13.   ,  25.   ,  12.   ,  24.   ,  11.   ,  27.   ],
       [ 11.   ,  25.   ,  14.   ,  25.   ,   7.   ,  20.   ,   9.   ,
         28.   ,   9.   ,  23.   ,  11.   ,  23.   ,  11.   ,  30.   ],
       [  9.   ,  30.   ,  15.   ,  26.   ,   9.   ,  27.   ,  14.   ,
         31.   ,   8.   ,  22.   ,  10.   ,  26.   ,  12.   ,  28.   ],
       [  6.   ,  28.   ,  12.   ,  31.   ,  14.   ,  27.   ,   9.   ,
         32.   ,   7.   ,  23.   ,  11.   ,  32.   ,   7.   ,  23.   ],

# 12. Find the average max temperature for the winter months in Jaipur.

In [86]:
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '20', '20', '30', '24', '29', '21', '27'],
       ['November', 'Week 2', '23', '29', '22', '32', '21', '23', '28'],
       ['November', 'Week 3', '28', '21', '32', '28', '30', '31', '23'],
       ['November', 'Week 4', '23', '23', '24', '29', '25', '24', '27'],
       ['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '20', '19', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '22', '21', '3', '5'],
       ['January', 'Week 3', '21', '18', '21', '19', '1

In [87]:
temp = max_temp[2:,2:].astype(int)
temp

array([[20, 20, 30, 24, 29, 21, 27],
       [23, 29, 22, 32, 21, 23, 28],
       [28, 21, 32, 28, 30, 31, 23],
       [23, 23, 24, 29, 25, 24, 27],
       [25, 25, 20, 28, 23, 23, 30],
       [30, 26, 27, 31, 22, 26, 28],
       [28, 31, 27, 32, 23, 32, 23],
       [28, 29, 22, 21, 27, 31, 25],
       [22, 21, 20, 19, 22,  7,  4],
       [22, 20, 21, 22, 21,  3,  5],
       [21, 18, 21, 19, 18,  7,  4],
       [19, 18, 20, 22, 19,  4,  8],
       [22, 19, 18, 19, 20, 71, 12],
       [19, 20, 18, 18, 22, 11,  7],
       [22, 19, 21, 21, 19, 10, 10],
       [21, 20, 21, 18, 20,  7,  9]])

In [88]:
np.max(temp)

71

In [89]:
np.mean(temp)

21.794642857142858

In [90]:
np.median(temp)

22.0

# 13. Find the weekly min avg temp for the month of Dec in Jaipur

In [91]:
min_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp', 'Min Temp'],
       ['November', 'Week 1', '11', '10', '9', '14', '6', '12', '12'],
       ['November', 'Week 2', '13', '13', '8', '-13', '6', '14', '11'],
       ['November', 'Week 3', '6', '14', '9', '8', '13', '6', '6'],
       ['November', 'Week 4', '6', '8', '14', '6', '13', '12', '11'],
       ['December', 'Week 1', '11', '14', '7', '9', '9', '11', '11'],
       ['December', 'Week 2', '9', '15', '9', '14', '8', '10', '12'],
       ['December', 'Week 3', '6', '12', '14', '9', '7', '11', '7'],
       ['December', 'Week 4', '7', '15', '11', '14', '12', '12', '14'],
       ['January', 'Week 1', '5', '8', '8', '7', '8', '2', '18'],
       ['January', 'Week 2', '4', '6', '6', '4', '4', '3', '20'],
       ['January', 'Week 3', '5', '7', '8', '4', '4', '3', '18'],
       ['January', 

In [92]:
dec_min_w1 = min_temp[6:7,2:].astype(int)
dec_min_w2 = min_temp[7:8,2:].astype(int)
dec_min_w3 = min_temp[8:9,2:].astype(int)
dec_min_w4 = min_temp[9:10,2:].astype(int)

In [93]:
dec_min_w4

array([[ 7, 15, 11, 14, 12, 12, 14]])

In [94]:
print('Minimum Average Temperature Week 1:',np.mean(dec_min_w1))
print('Minimum Average Temperature Week 2:',np.mean(dec_min_w2))
print('Minimum Average Temperature Week 3:',np.mean(dec_min_w3))
print('Minimum Average Temperature Week 4:',np.mean(dec_min_w4))

Minimum Average Temperature Week 1: 10.285714285714286
Minimum Average Temperature Week 2: 11.0
Minimum Average Temperature Week 3: 9.428571428571429
Minimum Average Temperature Week 4: 12.142857142857142


# 14. Find the overall avg temp for the months Dec and Jan


In [95]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27']], dtype='<U16')

In [96]:
cond_dec = data[0:,0]=='December'
dec_temp = data[cond_dec]
dec_temp = dec_temp[:,2:].astype(int)
dec_temp

array([[11, 25, 14, 25,  7, 20,  9, 28,  9, 23, 11, 23, 11, 30],
       [ 9, 30, 15, 26,  9, 27, 14, 31,  8, 22, 10, 26, 12, 28],
       [ 6, 28, 12, 31, 14, 27,  9, 32,  7, 23, 11, 32,  7, 23],
       [ 7, 28, 15, 29, 11, 22, 14, 21, 12, 27, 12, 31, 14, 25]])

In [97]:
jan_cond = data[:,0]=='January'
jan_temp = data[jan_cond]
jan_temp = jan_temp[:,2:].astype(int)
jan_temp

array([[ 5, 22,  8, 21,  8, 20,  7, 19,  8, 22,  2,  7, 18,  4],
       [ 4, 22,  6, 20,  6, 21,  4, 22,  4, 21,  3,  3, 20,  5],
       [ 5, 21,  7, 18,  8, 21,  4, 19,  4, 18,  3,  7, 18,  4],
       [ 6, 19,  2, 18,  7, 20,  8, 22,  8, 19,  7,  4, 20,  8]])

In [98]:
np.mean(dec_temp)

18.625

In [99]:
np.mean(jan_temp)

11.732142857142858

In [100]:
#Average temperature for Dec and Jan

np.mean(np.vstack((dec_temp,jan_temp)))


15.178571428571429

# 15. Find the least temp experienced by the city in the month of Dec and Jan. Also print the exact date( Day/Week/Month) for the same.

In [101]:
dec_jan_temp = np.vstack((dec_temp,jan_temp)) 
dec_jan_temp

array([[11, 25, 14, 25,  7, 20,  9, 28,  9, 23, 11, 23, 11, 30],
       [ 9, 30, 15, 26,  9, 27, 14, 31,  8, 22, 10, 26, 12, 28],
       [ 6, 28, 12, 31, 14, 27,  9, 32,  7, 23, 11, 32,  7, 23],
       [ 7, 28, 15, 29, 11, 22, 14, 21, 12, 27, 12, 31, 14, 25],
       [ 5, 22,  8, 21,  8, 20,  7, 19,  8, 22,  2,  7, 18,  4],
       [ 4, 22,  6, 20,  6, 21,  4, 22,  4, 21,  3,  3, 20,  5],
       [ 5, 21,  7, 18,  8, 21,  4, 19,  4, 18,  3,  7, 18,  4],
       [ 6, 19,  2, 18,  7, 20,  8, 22,  8, 19,  7,  4, 20,  8]])

In [102]:
cond_leat_temp = np.min(dec_jan_temp)
cond_leat_temp

2

In [103]:
d_j = np.hstack((data[6:14,0:2],dec_jan_temp[:,:]))

In [104]:
d_j = np.vstack((data[0:2,:],d_j))

In [105]:
d_j

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],
       ['December', 'Week 2', '9', '30', '15', '26', '9', '27', '14',
        '31', '8', '22', '10', '26', '12', '28'],
       ['December', 'Week 3', '6', '28', '12', '31', '14', '27', '9',
        '32', '7', '23', '11', '32', '7', '23'],
       ['December', 'Week 4', '7', '28', '15', '29', '11', '22', '14',
        '21', '12', '27', '12', '31', '14', '25'],
       ['January', 'Week 1', '5', '22', '8', '21', '8', '20', '7', '19',
        '8', '22', '2', '7', '18', '4'],
      

In [106]:
condn = d_j[:,2]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [107]:
condn = d_j[:,3]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [108]:
condn = d_j[:,4]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
        True])

In [109]:
d_j[condn]

array([['January', 'Week 4', '6', '19', '2', '18', '7', '20', '8', '22',
        '8', '19', '7', '4', '20', '8']], dtype='<U16')

In [110]:
condn = d_j[:,5]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [111]:
condn = d_j[:,6]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [112]:
condn = d_j[:,7]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [113]:
condn = d_j[:,8]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [114]:
condn = d_j[:,9]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [115]:
condn = d_j[:,10]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [116]:
condn = d_j[:,11]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [117]:
condn = d_j[:,12]=='2'
condn

array([False, False, False, False, False, False,  True, False, False,
       False])

In [118]:
d_j[condn]

array([['January', 'Week 1', '5', '22', '8', '21', '8', '20', '7', '19',
        '8', '22', '2', '7', '18', '4']], dtype='<U16')

In [119]:
condn = d_j[:,13]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

In [120]:
condn = d_j[:,15]=='2'
condn

array([False, False, False, False, False, False, False, False, False,
       False])

# 16. Find the max temp in the month of Feb and return its date(Day/Week/Month)


In [136]:
data[:2]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U16')

In [137]:
cond_feb = data[:,0]=='February'

In [138]:
feb_temp1 = data[cond_feb]
feb_temp1

array([['February', 'Week 1', '8', '22', '7', '19', '-10', '18', '11',
        '19', '12', '20', '12', '71', '21', '12'],
       ['February', 'Week 2', '8', '19', '10', '20', '12', '18', '10',
        '18', '10', '22', '8', '11', '19', '7'],
       ['February', 'Week 3', '9', '22', '11', '19', '7', '21', '11',
        '21', '9', '19', '7', '10', '19', '10'],
       ['February', 'Week 4', '11', '21', '7', '20', '11', '21', '12',
        '18', '11', '20', '12', '7', '21', '9']], dtype='<U16')

In [139]:
feb_temp2 = feb_temp1[:,2:].astype(int)

In [140]:
max_tem_feb = np.max(feb_temp2)

In [141]:
max_tem_feb

71

In [142]:
cond_1 = feb_temp1[:,2]=='71'
cond_1

array([False, False, False, False])

In [143]:
feb_temp1[cond_1]

array([], shape=(0, 16), dtype='<U16')

In [144]:
cond_1 = feb_temp1[:,3]=='71'
cond_1

array([False, False, False, False])

In [145]:
cond_1 = feb_temp1[:,4]=='71'
cond_1

array([False, False, False, False])

In [146]:
cond_1 = feb_temp1[:,5]=='71'
cond_1

array([False, False, False, False])

In [147]:
cond_1 = feb_temp1[:,6]=='71'
cond_1

array([False, False, False, False])

In [148]:
cond_1 = feb_temp1[:,7]=='71'
cond_1

array([False, False, False, False])

In [149]:
cond_1 = feb_temp1[:,8]=='71'
cond_1

array([False, False, False, False])

In [150]:
cond_1 = feb_temp1[:,9]=='71'
cond_1

array([False, False, False, False])

In [151]:
cond_1 = feb_temp1[:,10]=='71'
cond_1

array([False, False, False, False])

In [152]:
cond_1 = feb_temp1[:,11]=='71'
cond_1

array([False, False, False, False])

In [153]:
cond_1 = feb_temp1[:,12]=='71'
cond_1

array([False, False, False, False])

In [154]:
cond_1 = feb_temp1[:,13]=='71'
cond_1

array([ True, False, False, False])

In [155]:
feb_temp1[cond_1]

array([['February', 'Week 1', '8', '22', '7', '19', '-10', '18', '11',
        '19', '12', '20', '12', '71', '21', '12']], dtype='<U16')

In [156]:
cond_1 = feb_temp1[:,14]=='71'
cond_1

array([False, False, False, False])

In [157]:
cond_1 = feb_temp1[:,15]=='71'
cond_1

array([False, False, False, False])

# 17. Find the days in the month of Nov where the max temp of the day dropped below the avg temp of the month.



In [158]:
data[0:3]

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27']], dtype='<U16')

In [159]:
max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['', '', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp', 'Max Temp'],
       ['November', 'Week 1', '20', '20', '30', '24', '29', '21', '27'],
       ['November', 'Week 2', '23', '29', '22', '32', '21', '23', '28'],
       ['November', 'Week 3', '28', '21', '32', '28', '30', '31', '23'],
       ['November', 'Week 4', '23', '23', '24', '29', '25', '24', '27'],
       ['December', 'Week 1', '25', '25', '20', '28', '23', '23', '30'],
       ['December', 'Week 2', '30', '26', '27', '31', '22', '26', '28'],
       ['December', 'Week 3', '28', '31', '27', '32', '23', '32', '23'],
       ['December', 'Week 4', '28', '29', '22', '21', '27', '31', '25'],
       ['January', 'Week 1', '22', '21', '20', '19', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '22', '21', '3', '5'],
       ['January', 'Week 3', '21', '18', '21', '19', '1

In [160]:
cond_nov_temp = data[0:,0]=='November'
cond_nov_temp

array([False, False,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [161]:
nov_temp = data[cond_nov_temp]
nov_temp

array([['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27']], dtype='<U16')

In [162]:
nov_temp = nov_temp[:,2:].astype(int)

In [163]:
mean_nov = np.mean(nov_temp)
mean_nov

17.410714285714285

In [164]:
nov_max = max_temp[2:6,:]
nov_max

array([['November', 'Week 1', '20', '20', '30', '24', '29', '21', '27'],
       ['November', 'Week 2', '23', '29', '22', '32', '21', '23', '28'],
       ['November', 'Week 3', '28', '21', '32', '28', '30', '31', '23'],
       ['November', 'Week 4', '23', '23', '24', '29', '25', '24', '27']],
      dtype='<U16')

In [165]:
nov_max = nov_max[:,2:].astype(int)

In [166]:
nov_max.shape

(4, 7)

In [167]:
cond = nov_max<mean

In [168]:
cond

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [169]:
cond[cond]

array([], dtype=bool)

No days are there, where maximum temperature is lesser than avaerage temperature

......................................................

# 18. Convert the above dataset into an array where the weeks of the same month must be present in the same row, but belonging to different months should come in a row either below or above the selected month.


In [170]:
data


array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '11', '20', '10', '20', '9', '30', '14',
        '24', '6', '29', '12', '21', '12', '27'],
       ['November', 'Week 2', '13', '23', '13', '29', '8', '22', '-13',
        '32', '6', '21', '14', '23', '11', '28'],
       ['November', 'Week 3', '6', '28', '14', '21', '9', '32', '8',
        '28', '13', '30', '6', '31', '6', '23'],
       ['November', 'Week 4', '6', '23', '8', '23', '14', '24', '6',
        '29', '13', '25', '12', '24', '11', '27'],
       ['December', 'Week 1', '11', '25', '14', '25', '7', '20', '9',
        '28', '9', '23', '11', '23', '11', '30'],


# 19. The above data is appropriate for an audience who follow the metric system of measurement. Create an array that holds the same data but presented in Fahrenheit.


In [171]:
data_1 = data[2:,2:].astype(int)

In [172]:
data_1

array([[ 11,  20,  10,  20,   9,  30,  14,  24,   6,  29,  12,  21,  12,
         27],
       [ 13,  23,  13,  29,   8,  22, -13,  32,   6,  21,  14,  23,  11,
         28],
       [  6,  28,  14,  21,   9,  32,   8,  28,  13,  30,   6,  31,   6,
         23],
       [  6,  23,   8,  23,  14,  24,   6,  29,  13,  25,  12,  24,  11,
         27],
       [ 11,  25,  14,  25,   7,  20,   9,  28,   9,  23,  11,  23,  11,
         30],
       [  9,  30,  15,  26,   9,  27,  14,  31,   8,  22,  10,  26,  12,
         28],
       [  6,  28,  12,  31,  14,  27,   9,  32,   7,  23,  11,  32,   7,
         23],
       [  7,  28,  15,  29,  11,  22,  14,  21,  12,  27,  12,  31,  14,
         25],
       [  5,  22,   8,  21,   8,  20,   7,  19,   8,  22,   2,   7,  18,
          4],
       [  4,  22,   6,  20,   6,  21,   4,  22,   4,  21,   3,   3,  20,
          5],
       [  5,  21,   7,  18,   8,  21,   4,  19,   4,  18,   3,   7,  18,
          4],
       [  6,  19,   2,  18,   7,  20,   8, 

In [173]:
#ferh_cond = 1.8*C+32
data_2 = 1.8*data_1
data_2

array([[ 19.8,  36. ,  18. ,  36. ,  16.2,  54. ,  25.2,  43.2,  10.8,
         52.2,  21.6,  37.8,  21.6,  48.6],
       [ 23.4,  41.4,  23.4,  52.2,  14.4,  39.6, -23.4,  57.6,  10.8,
         37.8,  25.2,  41.4,  19.8,  50.4],
       [ 10.8,  50.4,  25.2,  37.8,  16.2,  57.6,  14.4,  50.4,  23.4,
         54. ,  10.8,  55.8,  10.8,  41.4],
       [ 10.8,  41.4,  14.4,  41.4,  25.2,  43.2,  10.8,  52.2,  23.4,
         45. ,  21.6,  43.2,  19.8,  48.6],
       [ 19.8,  45. ,  25.2,  45. ,  12.6,  36. ,  16.2,  50.4,  16.2,
         41.4,  19.8,  41.4,  19.8,  54. ],
       [ 16.2,  54. ,  27. ,  46.8,  16.2,  48.6,  25.2,  55.8,  14.4,
         39.6,  18. ,  46.8,  21.6,  50.4],
       [ 10.8,  50.4,  21.6,  55.8,  25.2,  48.6,  16.2,  57.6,  12.6,
         41.4,  19.8,  57.6,  12.6,  41.4],
       [ 12.6,  50.4,  27. ,  52.2,  19.8,  39.6,  25.2,  37.8,  21.6,
         48.6,  21.6,  55.8,  25.2,  45. ],
       [  9. ,  39.6,  14.4,  37.8,  14.4,  36. ,  12.6,  34.2,  14.4,
         

In [174]:
data_in_F = data_2+32

In [175]:
data_in_F

array([[ 51.8,  68. ,  50. ,  68. ,  48.2,  86. ,  57.2,  75.2,  42.8,
         84.2,  53.6,  69.8,  53.6,  80.6],
       [ 55.4,  73.4,  55.4,  84.2,  46.4,  71.6,   8.6,  89.6,  42.8,
         69.8,  57.2,  73.4,  51.8,  82.4],
       [ 42.8,  82.4,  57.2,  69.8,  48.2,  89.6,  46.4,  82.4,  55.4,
         86. ,  42.8,  87.8,  42.8,  73.4],
       [ 42.8,  73.4,  46.4,  73.4,  57.2,  75.2,  42.8,  84.2,  55.4,
         77. ,  53.6,  75.2,  51.8,  80.6],
       [ 51.8,  77. ,  57.2,  77. ,  44.6,  68. ,  48.2,  82.4,  48.2,
         73.4,  51.8,  73.4,  51.8,  86. ],
       [ 48.2,  86. ,  59. ,  78.8,  48.2,  80.6,  57.2,  87.8,  46.4,
         71.6,  50. ,  78.8,  53.6,  82.4],
       [ 42.8,  82.4,  53.6,  87.8,  57.2,  80.6,  48.2,  89.6,  44.6,
         73.4,  51.8,  89.6,  44.6,  73.4],
       [ 44.6,  82.4,  59. ,  84.2,  51.8,  71.6,  57.2,  69.8,  53.6,
         80.6,  53.6,  87.8,  57.2,  77. ],
       [ 41. ,  71.6,  46.4,  69.8,  46.4,  68. ,  44.6,  66.2,  46.4,
         

In [176]:
data_in_F1 = np.hstack((data[2:,0:2],data_in_F))

In [177]:
data_in_F2 = np.vstack((data[0:2,:],data_in_F1))
data_in_F2

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '51.8', '68.0', '50.0', '68.0', '48.2',
        '86.0', '57.2', '75.2', '42.8', '84.2', '53.6',
        '69.80000000000001', '53.6', '80.6'],
       ['November', 'Week 2', '55.400000000000006', '73.4',
        '55.400000000000006', '84.2', '46.4', '71.6',
        '8.599999999999998', '89.6', '42.8', '69.80000000000001', '57.2',
        '73.4', '51.8', '82.4'],
       ['November', 'Week 3', '42.8', '82.4', '57.2',
        '69.80000000000001', '48.2', '89.6', '46.4', '82.4',
        '55.400000000000006', '86.0', '42.8', '87.80000000000001',
        '42.8', '73.4'],
 