# 1. Write a program to iterate the first 10 numbers and in each iteration, print the sum of the current and previous number.

In [1]:
previous_num = 0
for i in range(0,10):
    
    sum_two_number = previous_num + i
    print(f'Current number {i} Previous Number {previous_num} Sum: {sum_two_number}')
    previous_num = i

Current number 0 Previous Number 0 Sum: 0
Current number 1 Previous Number 0 Sum: 1
Current number 2 Previous Number 1 Sum: 3
Current number 3 Previous Number 2 Sum: 5
Current number 4 Previous Number 3 Sum: 7
Current number 5 Previous Number 4 Sum: 9
Current number 6 Previous Number 5 Sum: 11
Current number 7 Previous Number 6 Sum: 13
Current number 8 Previous Number 7 Sum: 15
Current number 9 Previous Number 8 Sum: 17


# 2. Write a program to find how many times substring “Emma” appears in the given string.
Given:
str_x = "Emma is good developer. Emma is a writer"


In [2]:
str_x = "Emma is good developer. Emma is a writer"
print("Emma appeared",str_x.count("Emma"),"times.")

Emma appeared 2 times.


# 3. Create a new list from a two list using the following condition
Given a two list of numbers, write a program to create a new list such that the
new list should contain odd numbers from the first list and even numbers
from the second list.

In [71]:
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
def new_list():
    new_list = list()
    
    for i in list1:
      
        if i%2 !=0:
            new_list = i
    return new_list
    
print(new_list())

35


In [63]:
for n in list2:
    if n%2 == 0:
        new_list = n
    
print(new_list)

90


# 4. Print downward Half-Pyramid Pattern with Star (asterisk)

In [64]:
r = 6
for i in range(r,0,-1):
    for j in range(0, i-1):
        print('*', end = "")
    print('')

*****
****
***
**
*



# 5) Write a function called exponent(base, exp) that returns an int value of base raises to the power of exp.

In [6]:
a = int(input())
b = int(input())
exp_fun = pow(a,b)
print(f"{a} raises to power of {b}: {exp_fun}")

2
5
2 raises to power of 5: 32


# 6) Write a NumPy program to test whether none of the elements of a given array is zero

In [7]:
import numpy as np
arr = np.array([5,6,4,8,6,7,25,5])
for i in arr:
    if i != 0:
        print(True)
    else:
        False

True
True
True
True
True
True
True
True


In [8]:
0 in arr

False

# 7) . Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [9]:
a = np.zeros(10)
b = np.ones(10)
c = np.array([5,5,5,5,5,5,5,5,5,5])

In [10]:
d = np.concatenate((a,b,c),axis =0)

In [11]:
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
d.reshape(6,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# 8) Write a NumPy program to create an array of all the even integers from 30 to70.

In [13]:
arr = np.arange(30,71,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 9) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [14]:
arr = np.random.randint(1,25,25).reshape(5,5)
arr

array([[ 4,  6,  4, 17,  3],
       [13, 12, 20, 13, 14],
       [ 8,  2,  4,  5, 20],
       [24,  9, 19, 15, 14],
       [ 5, 12, 13,  5,  7]])

In [15]:
print("Sum of all elements of array:")
print(np.sum(arr))

Sum of all elements of array:
268


In [16]:
print("Sum of coulmns:")
print(np.sum(arr, axis = 0))

Sum of coulmns:
[54 41 60 55 58]


In [17]:
print("Sum of rows:\n",np.sum(arr,axis = 1))

Sum of rows:
 [34 72 39 81 42]


# 10) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [18]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 11) Write a NumPy program to sort a given array by row and column in ascending order.


In [19]:
arr = np.random.randint(10,35,25).reshape(5,5)
arr


array([[25, 10, 17, 21, 24],
       [24, 26, 31, 20, 11],
       [18, 18, 18, 34, 31],
       [34, 10, 21, 16, 31],
       [14, 31, 15, 19, 11]])

In [20]:
np.sort(arr,axis=0)

array([[14, 10, 15, 16, 11],
       [18, 10, 17, 19, 11],
       [24, 18, 18, 20, 24],
       [25, 26, 21, 21, 31],
       [34, 31, 31, 34, 31]])

In [21]:
np.sort(arr,axis=1)

array([[10, 17, 21, 24, 25],
       [11, 20, 24, 26, 31],
       [18, 18, 18, 31, 34],
       [10, 16, 21, 31, 34],
       [11, 14, 15, 19, 31]])

# 12) Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.


In [22]:
array_3d = np.random.randint(10,70,60).reshape(3,5,4)
array_3d

array([[[53, 41, 50, 66],
        [27, 17, 52, 53],
        [36, 26, 29, 32],
        [29, 17, 39, 52],
        [58, 15, 53, 13]],

       [[27, 34, 49, 48],
        [62, 64, 42, 56],
        [28, 66, 44, 57],
        [16, 33, 52, 16],
        [57, 38, 14, 23]],

       [[64, 19, 65, 31],
        [27, 49, 45, 20],
        [41, 69, 54, 27],
        [42, 18, 58, 29],
        [60, 59, 45, 47]]])

# 13) Write a NumPy program to swap rows and columns of a given array in reverse order.Write a NumPy program to multiply two given arrays of same size element-by-element

# 14) Write a NumPy program to print the NumPy version in your system.

In [25]:
np.__version__

'1.21.5'

# 15) Print max from axis 0 and min from axis 1 from the following 2-D array.

sampleArray =
numpy.array([[34,43,73],[82,22,12],[53,94,66]])


In [26]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [88]:
np.max(arr,axis = 0)

array([82, 94, 73])

In [89]:
np.min(arr,axis=1)

array([34, 12, 53])

# 18) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [44]:
arr_1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr_2 = np.array([[15 ,33, 24], [4 ,7, 1]])

In [45]:
arr = arr_1+arr_2
arr

array([[20, 39, 33],
       [25, 25, 28]])

In [46]:
np.square(arr)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

# 19) Write a NumPy program to compute the multiplication of two given matrixes.

In [47]:
arr_1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr_2 = np.array([[15 ,33, 24], [4 ,7, 1]])

In [49]:
mul = np.dot(arr_1,arr_2.T)
mul

array([[ 489,   71],
       [1557,  237]])

# 20) Write a NumPy program to find a matrix or vector norm.


In [56]:
arr = np.random.randint(5,20,4)

In [57]:
arr

array([ 6, 15,  6, 18])

In [58]:
np.linalg.norm(arr)

24.919871588754223

# 22) Write a NumPy program to add, subtract, multiply, divide arguments element-wise.


In [72]:
arr_1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr_2 = np.array([[15 ,33, 24], [4 ,7, 1]])

In [73]:
arr_1+arr_2

array([[20, 39, 33],
       [25, 25, 28]])

In [74]:
arr_1-arr_2

array([[-10, -27, -15],
       [ 17,  11,  26]])

In [75]:
arr_1*arr_2

array([[ 75, 198, 216],
       [ 84, 126,  27]])

In [76]:
arr_1/arr_2

array([[ 0.33333333,  0.18181818,  0.375     ],
       [ 5.25      ,  2.57142857, 27.        ]])

# 23) Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.

In [77]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [87]:
np.max(arr)

94

In [80]:
np.min(arr)

12

In [85]:
a = int(input())
print(np.where(arr>a))
print(np.where(arr<a))
print(np.where(arr==a))

34
(array([0, 0, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 0, 1, 2], dtype=int64))
(array([1, 1], dtype=int64), array([1, 2], dtype=int64))
(array([0], dtype=int64), array([0], dtype=int64))


# 24) Write a NumPy program to get the powers of an array values element-wise

In [91]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])
pow(arr,3)

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

# 25) Write a NumPy program to round array elements to the given number of decimals.


In [92]:
arr = np.random.randint(10,25,12).reshape(4,3)
arr

array([[19, 12, 16],
       [10, 23, 19],
       [20, 19, 18],
       [22, 18, 12]])

In [96]:
a = np.sin(arr)
a

array([[ 0.14987721, -0.53657292, -0.28790332],
       [-0.54402111, -0.8462204 ,  0.14987721],
       [ 0.91294525,  0.14987721, -0.75098725],
       [-0.00885131, -0.75098725, -0.53657292]])

In [98]:
np.round(a,2)

array([[ 0.15, -0.54, -0.29],
       [-0.54, -0.85,  0.15],
       [ 0.91,  0.15, -0.75],
       [-0.01, -0.75, -0.54]])

# 26) Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product

In [99]:
arr1 = np.random.randint(10,25,15).reshape(5,3)
arr1


array([[10, 21, 21],
       [24, 10, 19],
       [12, 17, 17],
       [13, 22, 10],
       [19, 11, 19]])

In [100]:
arr2 = np.random.randint(25,40,6).reshape(3,2)
arr2

array([[36, 39],
       [28, 31],
       [33, 28]])

In [102]:
np.dot(arr1,arr2)

array([[1641, 1629],
       [1771, 1778],
       [1469, 1471],
       [1414, 1469],
       [1619, 1614]])

# 27) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.


In [103]:
arr = np.random.randint(25,50,15).reshape(3,5)
arr

array([[39, 48, 49, 26, 44],
       [27, 27, 46, 37, 38],
       [36, 35, 37, 39, 46]])

In [104]:
np.sort(arr,axis=0)

array([[27, 27, 37, 26, 38],
       [36, 35, 46, 37, 44],
       [39, 48, 49, 39, 46]])

In [105]:
np.sort(arr,axis=1)

array([[26, 39, 44, 48, 49],
       [27, 27, 37, 38, 46],
       [35, 36, 37, 39, 46]])

In [108]:
np.sort(arr,axis=None)

array([26, 27, 27, 35, 36, 37, 37, 38, 39, 39, 44, 46, 46, 48, 49])